Initial merge to ONS repo
ONSdigital/dp-nlp-category-api pull request #2
Opened 2023-05-09 11:12 UTC by KamenDimitrov97

2023-05-11 11:28 UTC, lindenmckenzie reviewed
Some general comments prior to full review.

2023-05-11 11:28 UTC, lindenmckenzie commented on README.md
> +make run
there is no `make run` command in the makefile.

2023-06-01 08:08 UTC, philtweir requested changes
I'm not sure if you can see this before I submit it so, more to come, but keen you can begin working through!

2023-06-05 08:33 UTC, lindenmckenzie commented on Dockerfile.in
> +FROM python:3.9
I don't believe we have a standard so makes sense to go latest LTS version as you say.

2023-06-05 08:39 UTC, lindenmckenzie commented on ff_fasttext_api/healthcheck.py
> +        last_commit = subprocess.check_output(['git', 'rev-parse', 'HEAD'])
https://github.com/ONSdigital/dp-topic-api/blob/1eee0e9eb4cdd9ab5898eb1051d51095851812eb/Makefile#LL10C1-L11C1 <-- is done int he makefile.

2023-06-06 08:07 UTC, philtweir commented on translate_cache.py
This should live somewhere better, probably bonn-py`

2023-06-06 08:07 UTC, philtweir commented on tests/api/server_test.py
> +    # Create a mock CategoryManager object to simulate the FastText model
This is useful, but an integration test that uses the sample data with the real category manager (bonn) would be good -- for instance, there is no test guaranteeing that our assumed return structure is what bonn would send (interface mismatch is a common pitfall for an overly encapsulated test suite, but equally, we can't depend on the entire environment - hence, a minimal sample fifu model is in the code base)

2023-06-08 14:44 UTC, merged